// Generated by scripts/gen-logo.mjs — run `npm run logo`, do not edit by hand.

/**
 * The OrchestraAI mark: a terminal prompt on the front face of an extruded box.
 * Strokes inherit `currentColor`, so it themes with whatever chrome hosts it.
 *
 * Render it at **24px or larger**. Below that the extrusion collapses — at 16px
 * its strokes land under one pixel — and the mark also stops out-weighing the
 * icon buttons beside it, so a toolbar button reads as the brand instead.
 * Small rasters use the compact art in this script rather than this component.
 */
export function Logo({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 120 120"
      fill="none"
      stroke="currentColor"
      strokeWidth={9.5}
      strokeLinecap="round"
      strokeLinejoin="round"
      className={className}
      aria-hidden="true"
    >
      <path d="M53 35 L81 35 Q99 35 99 53 L99 81 Q99 99 81 99 L53 99 Q35 99 35 81 L35 53 Q35 35 53 35 Z" />
      <path d="M25.5 80.5 Q21 76 21 67 L21 39 Q21 21 39 21 L67 21 Q76 21 80.5 25.5" />
      <path d="M25.5 80.5 L39.5 94.5" />
      <path d="M25.5 25.5 L39.5 39.5" />
      <path d="M80.5 25.5 L94.5 39.5" />
      <path d="M52.78 70.55 L59.89 63.44 L52.78 56.33" />
      <path d="M67 77.67 L81.22 77.67" />
    </svg>
  )
}
